package Views;


import javax.swing.JOptionPane;
import java.sql.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JRadioButton;

/**
 *
 * @author Thimansa
 */
public class CourseFee extends javax.swing.JFrame {

    /**
     * Creates new form Payments
     */
    public CourseFee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        visa = new javax.swing.JRadioButton();
        mastercard = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        CVN_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        course_txt = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fee_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        number_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        month_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        year_txt = new javax.swing.JTextField();
        pay_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Make Your Payments");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 230, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Payment Methods");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        jPanel1.add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 360, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fee Amount:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        buttonGroup1.add(visa);
        visa.setForeground(new java.awt.Color(255, 255, 255));
        visa.setText("VISA");
        jPanel1.add(visa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        buttonGroup1.add(mastercard);
        mastercard.setForeground(new java.awt.Color(255, 255, 255));
        mastercard.setText("MASTERCARD");
        mastercard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mastercardActionPerformed(evt);
            }
        });
        jPanel1.add(mastercard, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student's ID No:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));
        jPanel1.add(CVN_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 90, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Course:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));
        jPanel1.add(course_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 360, -1));

        search_btn.setBackground(new java.awt.Color(0, 51, 255));
        search_btn.setForeground(new java.awt.Color(255, 255, 255));
        search_btn.setText("Search");
        search_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        jPanel1.add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 60, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CVN:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));
        jPanel1.add(fee_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 360, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Card Type:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));
        jPanel1.add(number_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 360, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Expiration Month:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));
        jPanel1.add(month_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 90, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Expiration Year:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, -1, -1));
        jPanel1.add(year_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 90, -1));

        pay_btn.setBackground(new java.awt.Color(0, 102, 204));
        pay_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pay_btn.setForeground(new java.awt.Color(255, 255, 255));
        pay_btn.setText("Pay");
        pay_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_btnActionPerformed(evt);
            }
        });
        jPanel1.add(pay_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 200, 40));

        cancel_btn.setBackground(new java.awt.Color(255, 0, 0));
        cancel_btn.setForeground(new java.awt.Color(255, 255, 255));
        cancel_btn.setText("Cancel");
        cancel_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 140, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Card Number:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, 20));
        jPanel1.add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 360, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mastercardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mastercardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mastercardActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:                                          
    try {
        int stid = Integer.parseInt(id_txt.getText()); 

        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/registration_db", "root", "");

        String query1 = "SELECT name, course_name FROM stregistration WHERE student_id = " + stid;
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(query1);

        if (rs.next()) {
            String studentName = rs.getString("name");
            String courseName = rs.getString("course_name");

            name_txt.setText(studentName);
            course_txt.setText(courseName);

            String query2 = "SELECT fee FROM courses1 WHERE course_name = '" + courseName + "'";
            ResultSet rs2 = st.executeQuery(query2);

            if (rs2.next()) {
                double fee = rs2.getDouble("fee");
                fee_txt.setText(String.valueOf(fee));
            } else  {
                fee_txt.setText("");
                JOptionPane.showMessageDialog(this, "Course fee not found.", "Fee Missing", JOptionPane.WARNING_MESSAGE);
            }

            rs2.close(); 
        } else {
            name_txt.setText("");
            course_txt.setText("");
            fee_txt.setText("");
            JOptionPane.showMessageDialog(this, "No student found with this ID.", "Not Found", JOptionPane.WARNING_MESSAGE);
        }

        rs.close();
        st.close();
        conn.close();
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Please enter a valid Student ID.", "Input Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_search_btnActionPerformed

    private void pay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_btnActionPerformed
        // TODO add your handling code here:private void pay_btnActionPerformed(java.awt.event.ActionEvent evt) {
    try {
        int stid = Integer.parseInt(id_txt.getText());
        String name = name_txt.getText();
        String course = course_txt.getText();
        double fee = Double.parseDouble(fee_txt.getText());

        String cardType = "";
        if (visa.isSelected()) {
            cardType = "VISA";
        } else if (mastercard.isSelected()) {
            cardType = "MASTERCARD";
        }

        String cardNumber = number_txt.getText();
        String expMonth = month_txt.getText();
        String expYear = year_txt.getText();
        String cvn = CVN_txt.getText();

        // Basic validation
        if (cardType.isEmpty() || cardNumber.isEmpty() || expMonth.isEmpty() || expYear.isEmpty() || cvn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill in all payment details", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/registration_db", "root", "");
        String sql = "INSERT INTO payments (student_id, student_name, course_name, fee, card_type, card_number, expiry_month, expiry_year, cvn) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, stid);
        ps.setString(2, name);
        ps.setString(3, course);
        ps.setDouble(4, fee);
        ps.setString(5, cardType);
        ps.setString(6, cardNumber);
        ps.setString(7, expMonth);
        ps.setString(8, expYear);
        ps.setString(9, cvn);

        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Payment successful!", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Clear fields
        number_txt.setText("");
        month_txt.setText("");
        year_txt.setText("");
        CVN_txt.setText("");
        buttonGroup1.clearSelection();

        conn.close();

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid input format.", "Input Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }


        
    }//GEN-LAST:event_pay_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:
                                                    
    // Clear input fields
    id_txt.setText("");
    name_txt.setText("");
    course_txt.setText("");
    fee_txt.setText("");

    number_txt.setText("");
    month_txt.setText("");
    year_txt.setText("");
    CVN_txt.setText("");

   
    buttonGroup1.clearSelection();

    // Optional: Show cancel feedback
    JOptionPane.showMessageDialog(this, "Payment form cleared.", "Cancelled", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_cancel_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
              this.dispose();
              new Dashboard().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CVN_txt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JTextField course_txt;
    private javax.swing.JTextField fee_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mastercard;
    private javax.swing.JTextField month_txt;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField number_txt;
    private javax.swing.JButton pay_btn;
    private javax.swing.JButton search_btn;
    private javax.swing.JRadioButton visa;
    private javax.swing.JTextField year_txt;
    // End of variables declaration//GEN-END:variables
}