package Views;


import Authorizations.stRegisteration;
import Authorizations.stLogin;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Thimansa
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        courses_btn = new javax.swing.JButton();
        reg_btn = new javax.swing.JButton();
        Payment_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        report_btn = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setUndecorated(true);
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ead images/Ambition Guru _ Logo Idea (1).jpg"))); // NOI18N
        jButton4.setText("Courses");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 250, 60));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ead images/Setting free icons designed by Pop Vectors (1).jpg"))); // NOI18N
        jButton5.setText("Enroll Now");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 250, 60));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ead images/Logout free icons designed by Andy Horvath (1).jpg"))); // NOI18N
        jButton6.setText("Log Out");
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 250, 60));

        jFrame1.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        courses_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        courses_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ead images/Ambition Guru _ Logo Idea (1).jpg"))); // NOI18N
        courses_btn.setText("View Courses");
        courses_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courses_btnActionPerformed(evt);
            }
        });
        jPanel1.add(courses_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 250, 60));

        reg_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reg_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ead images/Setting free icons designed by Pop Vectors (1).jpg"))); // NOI18N
        reg_btn.setText("Enroll Now");
        reg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_btnActionPerformed(evt);
            }
        });
        jPanel1.add(reg_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 250, 60));

        Payment_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Payment_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ead images/Icono De Pago Online Diseñado De Manera Creativa Y Sencilla Para La Frescura Para Usos De Aplicacion PNG ,dibujos  Antecedentes, La Banca, Black PNG y Vector para Descargar Gratis _ Pngtree (1).jpg"))); // NOI18N
        Payment_btn.setText("Payments");
        Payment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Payment_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Payment_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 250, 60));

        logout_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ead images/Logout free icons designed by Andy Horvath (1).jpg"))); // NOI18N
        logout_btn.setText("Log Out");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        jPanel1.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 250, 60));

        report_btn.setBackground(new java.awt.Color(204, 204, 204));
        report_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        report_btn.setText("Get Reports");
        report_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_btnActionPerformed(evt);
            }
        });
        jPanel1.add(report_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 250, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_btnActionPerformed
        // TODO add your handling code here:
       
            setVisible(false);
            new stRegisteration().setVisible(true);
        
        
    }//GEN-LAST:event_reg_btnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void Payment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Payment_btnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CourseFee().setVisible(true);
       
    }//GEN-LAST:event_Payment_btnActionPerformed

    private void courses_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courses_btnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new courses().setVisible(true);
        
    }//GEN-LAST:event_courses_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
          int a= JOptionPane.showConfirmDialog(null,"Do you want to log out?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new stLogin().setVisible(true);
        }
    }//GEN-LAST:event_logout_btnActionPerformed

    private void report_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_btnActionPerformed
    java.sql.Connection conn = null;
    try {
        // Possible locations for the report file (corrected to match your actual path)
        String[] possiblePaths = {
            "src/reports/stregistration_report.jrxml",
            "src\\reports\\stregistration_report.jrxml",
            "reports/stregistration_report.jrxml",
            "reports\\stregistration_report.jrxml"
        };
        String reportPath = null;
        java.io.File reportFile = null;

        // Find the correct path
        for (String path : possiblePaths) {
            reportFile = new java.io.File(path);
            System.out.println("Trying path: " + reportFile.getAbsolutePath());
            if (reportFile.exists()) {
                reportPath = path;
                System.out.println("Found report file at: " + reportPath);
                break;
            }
        }

        if (reportPath == null) {
            // Show all attempted paths for debugging
            StringBuilder pathsAttempted = new StringBuilder("Report file not found. Attempted paths:\n");
            for (String path : possiblePaths) {
                pathsAttempted.append("- ").append(new java.io.File(path).getAbsolutePath()).append("\n");
            }
            throw new Exception(pathsAttempted.toString());
        }

        System.out.println("Using report file: " + reportPath);

        // Establish database connection (update with your DB details)
        conn = java.sql.DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/registration_db", "root", ""
        );

        // Compile and generate report
        System.out.println("Compiling report...");
        net.sf.jasperreports.engine.JasperReport jasperReport = net.sf.jasperreports.engine.JasperCompileManager.compileReport(reportPath);

        // Create parameters map (empty for now, but can be used for filtering)
        java.util.Map<String, Object> parameters = new java.util.HashMap<>();

        System.out.println("Filling report with data...");
        net.sf.jasperreports.engine.JasperPrint jasperPrint = net.sf.jasperreports.engine.JasperFillManager.fillReport(jasperReport, parameters, conn);

        System.out.println("Displaying report...");
        net.sf.jasperreports.view.JasperViewer.viewReport(jasperPrint, false);

    } catch (org.xml.sax.SAXParseException ex) {
        String error = "Report XML parsing failed: " + ex.getMessage() +
                      "\nThis usually means:\n1. JRXML file has compatibility issues\n2. Wrong JasperReports version\n" +
                      "Try using a simpler JRXML file or update JasperReports library.";
        System.err.println(error);
        javax.swing.JOptionPane.showMessageDialog(this, error, "Report XML Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (net.sf.jasperreports.engine.JRException ex) {
        String error = "Report generation failed: " + ex.getMessage();
        System.err.println(error);
        javax.swing.JOptionPane.showMessageDialog(this, error, "Report Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        String error = "Unexpected error: " + ex.getMessage();
        System.err.println(error);
        ex.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, error, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } finally {
        if (conn != null) {
            try {
                conn.close();
                System.out.println("Database connection closed.");
            } catch (Exception e) {
                System.err.println("Error closing connection: " + e.getMessage());
            }
        }
    }
}//GEN-LAST:event_report_btnActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Payment_btn;
    private javax.swing.JButton courses_btn;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton reg_btn;
    private javax.swing.JButton report_btn;
    // End of variables declaration//GEN-END:variables
}
