package Authorizations;


import Views.Dashboard;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.sql.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JRadioButton;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Thimansa
 */
public class stLogin extends javax.swing.JFrame {

    /**
     * Creates new form stLogin
     */
    public stLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pwd = new javax.swing.JPasswordField();
        login_btn = new javax.swing.JButton();
        close_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 168, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 80, -1));

        email_txt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });
        jPanel1.add(email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 301, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 80, -1));

        pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdActionPerformed(evt);
            }
        });
        jPanel1.add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 301, -1));

        login_btn.setBackground(new java.awt.Color(0, 102, 255));
        login_btn.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        login_btn.setForeground(new java.awt.Color(255, 255, 255));
        login_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ead images/Login 01 Icon _ Hugeicons (1).jpg"))); // NOI18N
        login_btn.setText("Login");
        login_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        jPanel1.add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 163, 44));

        close_btn.setBackground(new java.awt.Color(255, 51, 51));
        close_btn.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        close_btn.setText("Close");
        close_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });
        jPanel1.add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, 84, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student Registration System");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 244, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ead images/_Professional Online Education Logo Design – Mentor Branding Inspiration_ (2).jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, -30, 500, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        // TODO add your handling code here:
           String email=email_txt.getText();
           String Password=pwd.getText();
           String query; //to get the sql query string
 
    // Check the entered credentials
     if(email.equals("abc@gmail.com")&& Password.equals("123"))
                 {
                 stLogin f2 =new stLogin();
                 f2.setVisible(true);
                 this.dispose();
                 }
     else if (email.isEmpty()|| Password.isEmpty()) {
          JOptionPane.showMessageDialog(this, "All fields are required","Login Error",JOptionPane.ERROR_MESSAGE);
          return;
          }
     
        try
        {
           Class.forName("com.mysql.cj.jdbc.Driver");//Loads the MySQL database driver so Java can communicate with the database.
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/registration_db","root",""); //Connects to the database and creates a Statement object to run SQL commands.
            Statement st = conn.createStatement();

            query = "SELECT * FROM login WHERE email = '" + email + "' AND password ='" + Password +"'";
            ResultSet rs=st.executeQuery(query);
                 
         if(rs.next()){
             
             JOptionPane.showMessageDialog(this,"Login successful","success",JOptionPane.INFORMATION_MESSAGE);
             
                this.dispose();
                Dashboard dash= new Dashboard();
                dash.setVisible(true);
            }
        else{
            JOptionPane.showMessageDialog(null,"Entered email or password is incorrect","Login Error",JOptionPane.YES_OPTION);
            }
           conn.close();
    }catch(Exception e){
        System.out.println("Error occured:" +e.getMessage());
    }
  

    
    }//GEN-LAST:event_login_btnActionPerformed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        // TODO add your handling code here:
         int a=JOptionPane.showConfirmDialog(null,"Do you want to close application?","select",JOptionPane.YES_NO_OPTION);
         if(a==0){
             System.exit(0);
         }
    }//GEN-LAST:event_close_btnActionPerformed

    private void pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdActionPerformed

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_btn;
    private javax.swing.JTextField email_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_btn;
    private javax.swing.JPasswordField pwd;
    // End of variables declaration//GEN-END:variables
}
