package Authorizations;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import Views.Dashboard;
import javax.swing.JOptionPane;
import java.sql.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JRadioButton;

/**
 *
 * @author Thimansa
 */

public class stRegisteration extends javax.swing.JFrame {

    /**
     * Creates new form stRegisteration
     */
    public stRegisteration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        age_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        mobile_txt = new javax.swing.JTextField();
        male_rbtn = new javax.swing.JRadioButton();
        female_rbtn = new javax.swing.JRadioButton();
        add_txt = new javax.swing.JTextField();
        update_btn = new javax.swing.JButton();
        submit_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cmbox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Registration");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 235, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Full Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 100, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 57, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 90, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 70, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mobile:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 80, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 80, -1));
        jPanel1.add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 300, 30));
        jPanel1.add(age_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 230, 30));
        jPanel1.add(email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 230, 30));

        mobile_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobile_txtActionPerformed(evt);
            }
        });
        jPanel1.add(mobile_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 230, 30));

        buttonGroup.add(male_rbtn);
        male_rbtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        male_rbtn.setForeground(new java.awt.Color(255, 255, 255));
        male_rbtn.setText("Male");
        male_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male_rbtnActionPerformed(evt);
            }
        });
        jPanel1.add(male_rbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 100, 20));

        buttonGroup.add(female_rbtn);
        female_rbtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        female_rbtn.setForeground(new java.awt.Color(255, 255, 255));
        female_rbtn.setText("Female");
        female_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_rbtnActionPerformed(evt);
            }
        });
        jPanel1.add(female_rbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 100, 20));

        add_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_txtActionPerformed(evt);
            }
        });
        jPanel1.add(add_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 270, 60));

        update_btn.setBackground(new java.awt.Color(204, 204, 204));
        update_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update_btn.setText("Update");
        update_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel1.add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 120, 40));

        submit_btn.setBackground(new java.awt.Color(0, 51, 255));
        submit_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        submit_btn.setText("Submit");
        submit_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(submit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 160, 40));

        delete_btn.setBackground(new java.awt.Color(255, 0, 0));
        delete_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_btn.setText("Delete");
        delete_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jPanel1.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 90, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 384, 160, 30));

        cmbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboxActionPerformed(evt);
            }
        });
        jPanel1.add(cmbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 300, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Course:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
        String course_name = "";
        String name;
        int age;
        String email;
        int mobile;
        String address;
        String gender = "";

        buttonGroup.add(male_rbtn);
        buttonGroup.add(female_rbtn);
        String query;

        // Connect to the DB
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            String url = "jdbc:mysql://localhost:3306/registration_db";
            String user = "root";
            String pass = "";

            Connection conn = DriverManager.getConnection(url, user, pass);
            Statement st = conn.createStatement();

            // Validate input fields
            if ("".equals(cmbox.getSelectedItem())) {
                JOptionPane.showMessageDialog(new JFrame(), "Select a course", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(name_txt.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Enter the full name", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(age_txt.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Enter age", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(email_txt.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Enter email", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(mobile_txt.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Enter mobile number", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(add_txt.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Enter address", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (!male_rbtn.isSelected() && !female_rbtn.isSelected()) {
                JOptionPane.showMessageDialog(this, "Select gender", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                // Collect data
                name = name_txt.getText();
                age = Integer.parseInt(age_txt.getText());
                email = email_txt.getText();
                address = add_txt.getText();
                mobile = Integer.parseInt(mobile_txt.getText());
                course_name = (String) cmbox.getSelectedItem();

                if (male_rbtn.isSelected()) {
                    gender = "male";
                } else if (female_rbtn.isSelected()) {
                    gender = "female";
                }

                // Correct SQL syntax
                query = "INSERT INTO stRegistration (course_name, name, age, email, mobile, address, gender) "
                        + "VALUES ('" + course_name + "','" + name + "'," + age + ",'" + email + "'," + mobile + ",'" + address + "','" + gender + "')";

                st.executeUpdate(query);

                // Clear form
                name_txt.setText("");
                age_txt.setText("");
                email_txt.setText("");
                mobile_txt.setText("");
                add_txt.setText("");
                buttonGroup.clearSelection();
                cmbox.setSelectedIndex(-1); // Instead of removeAllItems()

                JOptionPane.showMessageDialog(new JFrame(), "Successfully registered.", "Success", JOptionPane.INFORMATION_MESSAGE);
                conn.close();
            }

        } catch (Exception e) {
            System.out.println("Can't connect to database: " + e.getMessage());
        }
    


        
    }//GEN-LAST:event_submit_btnActionPerformed

    private void mobile_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobile_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobile_txtActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        
    String name = name_txt.getText();

    // Check if ID is empty
    if ("".equals(name)) {
        JOptionPane.showMessageDialog(this, "Enter Student name to delete", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Confirm delete
    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Confirm", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/registration_db", "root", "");
        Statement st = conn.createStatement();

        String deleteQuery = "DELETE FROM stRegistration WHERE name='" + name + "'";
        int rowsDeleted = st.executeUpdate(deleteQuery);

        if (rowsDeleted > 0) {
            JOptionPane.showMessageDialog(this, "Record deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            // Clear form fields
      
            name_txt.setText("");
            age_txt.setText("");
            email_txt.setText("");
            mobile_txt.setText("");
            add_txt.setText("");
            buttonGroup.clearSelection();
            cmbox.removeAllItems();
        } else {
            JOptionPane.showMessageDialog(this, "No record found with this Student Name", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        String course_name = (String) cmbox.getSelectedItem();
        String name = name_txt.getText().trim();
        String ageStr = age_txt.getText().trim();
        String mobileStr = mobile_txt.getText().trim();
        String email = email_txt.getText().trim();
        String address = add_txt.getText().trim();
        String gender = "";


    if (name.isEmpty() || ageStr.isEmpty() || mobileStr.isEmpty() || email.isEmpty() || address.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill in all required fields.");
        return;
    }
    else if(!male_rbtn.isSelected() && !female_rbtn.isSelected()) {
        JOptionPane.showMessageDialog(this, "Select gender", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

        // Assign gender
    else if (male_rbtn.isSelected()) {
            gender = "male";
        } else if (female_rbtn.isSelected()) {
            gender = "female";
        }

    int age, mobile;
    try {
        age = Integer.parseInt(ageStr);
        mobile = Integer.parseInt(mobileStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter valid numbers for age and mobile.");
        return;
    }

        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/registration_db", "root", "");
        Statement st = conn.createStatement();

       String updateQuery = "UPDATE stRegistration SET name='" + name + "', age='" + age + "', email='" +email+"',mobile='" + mobile + "', address='" + address + "', gender='" + gender+ "',course_name ='" + course_name + "' WHERE name='" + name+ "'";

        int rowsAffected = st.executeUpdate(updateQuery);

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Record updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No record found with this name.", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }


        
    }//GEN-LAST:event_update_btnActionPerformed

    private void female_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_rbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_female_rbtnActionPerformed

    private void male_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male_rbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_male_rbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //close the current registeration form
        this.dispose();
       new Dashboard().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void add_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_txtActionPerformed

    private void cmboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboxActionPerformed
        // TODO add your handling code here:
       try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            ResultSet rs;
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/registration_db","root",""); 
            Statement st = conn.createStatement();
             
            String cName=(String)cmbox.getSelectedItem();
            String query= "SELECT * FROM courses1 WHERE course_name='" + cName + "'";
           rs=st.executeQuery(query);
    }
       catch(Exception e){
            System.out.println("Error occured:" +e.getMessage());
        }
    }//GEN-LAST:event_cmboxActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         try{
                 Class.forName("com.mysql.cj.jdbc.Driver");
                 ResultSet rs;
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/registration_db","root",""); 
                Statement st = conn.createStatement();
                String query = "SELECT course_name FROM courses1"; 
                rs=st.executeQuery(query);
            
            while(rs.next()){
                cmbox.addItem(rs.getString("course_name"));
            }
       }
       catch(Exception e){
               System.out.println("Error occured:" +e.getMessage());
    
               }
    }//GEN-LAST:event_formWindowOpened




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add_txt;
    private javax.swing.JTextField age_txt;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cmbox;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTextField email_txt;
    private javax.swing.JRadioButton female_rbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male_rbtn;
    private javax.swing.JTextField mobile_txt;
    private javax.swing.JTextField name_txt;
    private javax.swing.JButton submit_btn;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
